### ISSUE TITLE
Projects, Experiences, References, Artifacts should all come back with null values instead of back-end determined presents.

### ISSUE THREAD

**Issue by philbaylog** [bcary/Vestn_Backend#19]
Idk how you would even go about checking if a user updated the title or not (for profile score) if these didn't start at null. String checking would be a bitch (esp if these values changed), take a while, and not be 100% accurate (what if i want a project to be named New Project?).

The only thing that should come back with a default is something that is 100% necessary: project privacy. There is an inherent privacy built into a null value so we might as well let the user know what that is...default=private. (down the road, default=whatever the user has in their settings: Make New Projects Private [] checkbox in settings).

**Comment by bcary** [comment]
All default values have been set to null, save for the artifact title, which defaults to the fileName of the Artifact uploaded
