### ISSUE TITLE
Can't create reference (comes back with error: can't create 'experience')..and fails

### ISSUE THREAD

**Issue by philbaylog** [bcary/Vestn_Backend#20]
Message: "Something went wrong while adding the experience"
Reponse: null
Success: false
**proto**: Object

Also, the jsfiddle points to localhost NOT vestndev.

**Comment by bcary** [comment]
Add Reference has been fixed. In the process of removing the default values, a null reference exception was created when 'videoLink' was null. This issue has been rectified
