### ISSUE TITLE
Only requesting certain parameters from GetProfile does not work

### ISSUE THREAD

**Issue by philbaylog** [bcary/Vestn_Backend#24]
If it does, then make a jsfiddle to prove it because i can't figure it out.

**Comment by bcary** [comment]
Phil, you MUST have the 'traditional' parameter set to 'true' on the ajax call for an array of strings to make it to the backend. My bad, I thought I had mentioned that to you, and the example fiddle where the traditional parameter was set was for GetUserInformation, so my bad again. You can find another example for GetProfile here: http://jsfiddle.net/zfk4m/2/ . 

I'll now be assigning this bug to you.

**Comment by philbaylog** [comment]
Ok perf

**Comment by philbaylog** [comment]
Nope. If I'm the owner even if I specify traditional:true the object that comes back is completely filled out.
If i make the request as another user it does function properly

**Comment by bcary** [comment]
fixed
