### ISSUE TITLE
Upload Resume not working

### ISSUE THREAD

**Issue by philbaylog** [bcary/Vestn_Backend#8]
I save it, get a success message back with a response:
latest

http://vestnstaging.blob.core.windows.net/pdfs/https://vestnstaging.blob.core.windows.net/pdfs/9163ac21-46ff-418e-8ae4-137c0a431f57.pdf

but this is a broken link every time.

**Comment by bcary** [comment]
Duplicate URI location identifier. Bug fix is now live.
